# Generated by Django 4.1.7 on 2023-03-16 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='post',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='post',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='post',
            new_name='event',
        ),
    ]
