# Generated by Django 4.1.7 on 2023-03-16 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
        ('feedback', '0002_rename_post_favorite_event_rename_post_like_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='event.event'),
        ),
        migrations.AlterField(
            model_name='like',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='event.event'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='event.event'),
        ),
    ]
