# Generated by Django 4.1.7 on 2023-03-16 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_alter_favorite_event_alter_like_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='category',
            new_name='event',
        ),
    ]
