# Generated by Django 4.1.7 on 2023-03-17 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.TextField(default='1'),
            preserve_default=False,
        ),
    ]
