# Generated by Django 4.1.7 on 2023-03-17 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0006_comment_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='id',
        ),
        migrations.AddField(
            model_name='comment',
            name='scomment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='feedback.comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
