# Generated by Django 4.1.7 on 2023-03-17 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0007_remove_comment_id_comment_scomment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='scomment',
        ),
        migrations.AddField(
            model_name='comment',
            name='id',
            field=models.BigAutoField(auto_created=True, default='1', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(),
        ),
    ]
