# Generated by Django 4.1.7 on 2023-03-14 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
