# Generated by Django 4.1.7 on 2023-03-16 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_event_delete_soup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='category',
        ),
        migrations.RemoveField(
            model_name='event',
            name='owner',
        ),
    ]
