# Generated by Django 4.1.7 on 2023-03-16 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_alter_favorite_event_alter_like_category_and_more'),
        ('category', '0005_remove_event_category_remove_event_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
