# Generated by Django 4.1.7 on 2023-03-20 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_remove_event_category_remove_event_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
