# Generated by Django 4.1.7 on 2023-03-20 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='amount',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
