# Generated by Django 4.1.7 on 2023-03-20 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='owner',
        ),
    ]
