# Generated by Django 4.1.7 on 2023-03-16 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_event_delete_soup'),
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='category.category'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
